before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: WM/rp1+L71GzNYcYr3hG4wSCc1pypdqt+pdBIatY6Kzdmicsm64obvI7NEmw987n9tFLdNnuteZinC7j4bRNF+DxXIvq+Z4qZIpNdalkZ+TUXCZVzyzepE+IExa9pA5TXUOMtXvwSQ1JQqRl8D6k8+cksmnPdrClzLqGDBfl7n0SZkT3kUJF1z2seLtGJRMl4CMl7+8KcnHB0DVgzd0hHPxcXwKnM6FquziH5UP3Ix2LKldxK1eD6Pfh9O0kvVhybntKzaRvZECRCeyT8//DQSrt9oHE0Za9ZMyJSUCf4ZRJ6dduCgUMCsrvvOhbNM3LV2EipPyEMApyCN9vpHn5xoJ6zbK5r5s7kYr+ykrSGXtO0Ps3ejP5/iesOuwrtEbd64oifsx/58Mb+FNbM2zHb7ktLuptJkEx+wozxlwWkt3IovsvOOfUvqIL++QQttuyk+Zc/a+fmEPBAWdmRg6o486spAkQGJVaGh9HAuanqqEEcD0bJheTavXHDLWKjzs6u7o2EtnGkbXScrZDOgShYvLCOOvtIQ2VI1es3aSMdLg6BazRL4/395gdR+wyg1tTKQJ3+hzdqy8QG5nIl9Fv47QS8cT/vRrxLLV9l7uq4xwYgbUE3uaj1w3tKtO90uZCy62fZZfbsKB5jTQhKgKmvTi2DIy8a9Kq0cmYsdeEg0k= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
